import { describe, expect, it } from "vitest";
import { rankContext } from "../../../src/application/context/rank-context.js";
import type { CurrentStatement } from "../../../src/domain/knowledge.js";

const repositoryBelief: CurrentStatement = { id: "bel_1", revisionId: "rev_1", kind: "belief", body: "Auth uses cookies", status: "active", scope: { kind: "repository" }, attributes: { confidence: 0.8 }, revisionNumber: 1, createdAt: "2026-01-01T00:00:00Z" };
const generatedCommitment: CurrentStatement = { id: "com_1", revisionId: "rev_2", kind: "commitment", body: "Do not edit generated clients", status: "accepted", scope: { kind: "path", prefix: "generated" }, attributes: { rationale: "Generated by CI", authority: { kind: "human", id: "owner" } }, revisionNumber: 1, createdAt: "2026-01-01T00:00:00Z" };

describe("context ranking", () => {
  it("fuses semantic hits and excludes unrelated path commitments", () => {
    const items = rankContext({ lexical: [], semantic: [{ statementId: repositoryBelief.id, score: 0.9 }], fallback: [generatedCommitment], resolveStatement: (id) => id === repositoryBelief.id ? repositoryBelief : undefined, paths: ["src/auth.ts"], maxItems: 12 });
    expect(items.map((item) => item.id)).toEqual([repositoryBelief.id]);
  });
});
